name: CI Calc

on:
  push:
  pull_request:

jobs:
  build-test-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Installer Composer
        run: |
          curl -sS https://getcomposer.org/installer \
            | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Installer les dépendances (phpDocumentor)
        run: composer install --no-interaction --prefer-dist

      # 1) Lint : vérifier que le PHP est syntaxiquement valide
      - name: Lint PHP (php -l)
        run: php -l calc.php

      # 2) Test de bug : vérifier que la calculatrice ne "bug" pas
      - name: Test de comportement (2 + 2 = 4)
        run: ./test_bug.sh

      # 3) Génération de la documentation
      - name: Générer la documentation (phpDocumentor)
        run: vendor/bin/phpdoc -d . -t docs/api

      # 4) Sauvegarder la doc comme artefact
      - name: Upload de la doc générée
        uses: actions/upload-artifact@v4
        with:
          name: calc-api-docs
          path: docs/api
